/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    ProductsAdmin: typeof import('./src/components/ProductsAdmin.vue')['default']
    ProductsDepot: typeof import('./src/components/Products-depot.vue')['default']
    ProductsEconomat: typeof import('./src/components/Products-economat.vue')['default']
    ProductsEntretien: typeof import('./src/components/Products-entretien.vue')['default']
    ProductsEntretienAc: typeof import('./src/components/Products-entretien-ac.vue')['default']
    ProductsEntretienAcademie: typeof import('./src/components/Products-entretien-academie.vue')['default']
    ProductsEntretienAhdv: typeof import('./src/components/Products-entretien-ahdv.vue')['default']
    ProductsEntretienAvernas: typeof import('./src/components/Products-entretien-avernas.vue')['default']
    ProductsEntretienBibli: typeof import('./src/components/Products-entretien-bibli.vue')['default']
    ProductsEntretienDepot: typeof import('./src/components/Products-entretien-depot.vue')['default']
    ProductsEntretienEmploi: typeof import('./src/components/Products-entretien-emploi.vue')['default']
    ProductsEntretienGh: typeof import('./src/components/Products-entretien-gh.vue')['default']
    ProductsEntretienLsr: typeof import('./src/components/Products-entretien-lsr.vue')['default']
    ProductsEntretienMds: typeof import('./src/components/Products-entretien-mds.vue')['default']
    ProductsEntretienMerdorp: typeof import('./src/components/Products-entretien-merdorp.vue')['default']
    ProductsEntretienMoxhe: typeof import('./src/components/Products-entretien-moxhe.vue')['default']
    ProductsEntretienSaline: typeof import('./src/components/Products-entretien-saline.vue')['default']
    ProductsEntretienThisnes: typeof import('./src/components/Products-entretien-thisnes.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
